Stdlib Functions for Tests Accessible with Bodies
jesyspa/kotlin pull request #220
Opened 2024-07-08 06:54 UTC by GrigoriiSolnyshkin

Our plugin currently cannot inline functions like `run`, `let` etc. from standard library because it does not have access to their implementation (i.e. fir body). This PR introduces a (half-) measure for our tests: just use ```// REPLACE_STDLIB_EXTENSIONS``` in order to use our own implementations which are basically copied from stdlib.

2024-07-08 07:24 UTC, jesyspa requested changes
Looks good in general, thanks for the quick fix.  Could you please also add a test that uses this?

2024-07-12 09:22 UTC, GrigoriiSolnyshkin commented
> Looks good in general, thanks for the quick fix. Could you please also add a test that uses this?

The problem with tests here is that these functions don't actually work without this other PR. I added `check` with empty implementation and included it in some test though.

2024-07-12 14:49 UTC, jesyspa commented
Let's wait for the other PR to land then, I'm afraid tests won't end up happening otherwise

2024-07-17 13:50 UTC, jesyspa approved these changes

2024-08-25 23:02 UTC, merged