Add a builder for `TypeEmbedding`s
jesyspa/kotlin pull request #229
Opened 2024-07-17 13:15 UTC by jesyspa

Previously, we used the type embeddings directly in the code.  This makes changing their representation quite hard; this PR introduces a builder that lets us hide the implementation details.

This isn't quite perfect; we sometimes still check what subtype a particular embedding is.  Getting rid of that entirely would be an even bigger change, though.

2024-07-24 13:20 UTC, GrigoriiSolnyshkin requested changes
Overall calls of `buildType` seem redundant for primitive types. It would still be nice to have a possibility to use single-token references for them. And the thing that worries me a little bit is that in this paradigm some things become quite complex. For example if I have a `TypeEmbedding` what is a short way to create a nullable version of it?

2024-07-24 13:30 UTC, jesyspa commented
Sorry, I should have given more details.  The motivation here is to be able to split `TypeEmbedding` into a `PretypeEmbedding` and a bunch of flags like nullable, unique, etc.  That makes constructing type embeddings more messy, hence this builder.

> Overall calls of buildType seem redundant for primitive types.  It would still be nice to have a possibility to use single-token references for them.

At the moment, yes; in the future, it will mean that you write `buildType { int() }` instead of `TypeEmbedding(IntPretypeEmbedding, nullable = false, unique = false, ...)`. 

We could make special functions like `buildIntType` to make this easier, but I'm not sure the special case is special enough to be worth it.

> And the thing that worries me a little bit is that in this paradigm some things become quite complex. For example if I have a TypeEmbedding what is a short way to create a nullable version of it?

`TypeEmbedding` has `getNullable` for this, which should already be the preferred way.  With unique and borrow added into the mix, I think this will make it easier.

2024-07-24 19:00 UTC, francescoo22 commented on plugins/formal-verification/formver.core/src/org/jetbrains/kotlin/formver/embeddings/TypeBuilder.kt
> +    }
nit: body can be an expression

2024-07-24 19:02 UTC, francescoo22 commented
Looks good to me overall!
I think this should work well also with borrowed and unique flags for classes and functions declaration.

2024-07-24 19:03 UTC, francescoo22 approved these changes

2024-07-26 12:28 UTC, GrigoriiSolnyshkin approved these changes
Seems good!

2024-07-26 12:34 UTC, GrigoriiSolnyshkin commented
> We could make special functions like `buildIntType` to make this easier, but I'm not sure the special case is special enough to be worth it.

I feel like we write them quite often, especially `BooleanTypeEmbedding` and `UnitTypeEmbedding` and almost always without `nullable` flag. But yeah, I'm not so sure about `unique` and `borrowed` of course.

2024-07-26 12:49 UTC, merged

2024-07-26 12:50 UTC, jesyspa commented
If we find the need we can always introduce abbreviations.